### ISSUE TITLE
Support handlers for unknown properties, useful for error handling

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gson#188]
```
What steps will reproduce the problem?
1. create a JSON string containing extra attributes
2. invoke Gson.fromJson supplying a class with fewer elements
3. GSON successfully instantiates the class without protesting about the 
existence of extra attributes in the string.

What is the expected output? What do you see instead?
1. define class A containing two fields: name and surname
2. define class B containing only one field: name
3. transform an instance of class A to Json string and use the Json string 
to create an instance of class B.

GSON doesn't complain. Even if this is the intended behavior, shouldn't 
there be an option to enforce stricter parsing?

What version of the product are you using? On what operating system?
gson-1.4

Please provide any additional information below.


```

Original issue reported on code.google.com by `mperdik...@gmail.com` on 22 Jan 2010 at 10:13

Attachments:
- [Converter.java](https://storage.googleapis.com/google-code-attachments/google-gson/issue-188/comment-0/Converter.java)

**Comment by mcerina** [comment]
I submitted pull request https://github.com/google/gson/pull/660 for this

**Comment by avarabyeu** [comment]
Any updates on this issue? looking forward for the fix...

**Comment by pratapkishorevarma** [comment]
Is there a workaround for this issue which we can do until a fix is provided?

**Comment by ikus060** [comment]
I manage to workaround this issue using a class similar to the following:
```
public class ValidatorAdapterFactory implements TypeAdapterFactory {

    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
        // If the type adapter is a reflective type adapter, we want to modify the implementation using reflection. The
        // trick is to replace the Map object used to lookup the property name. Instead of returning null if the
        // property is not found, we throw a Json exception to terminate the deserialization.
        TypeAdapter<T> delegate = gson.getDelegateAdapter(this, type);

        // Check if the type adapter is a reflective, cause this solution only work for reflection.
        if (delegate instanceof ReflectiveTypeAdapterFactory.Adapter) {

            try {
                // Get reference to the existing boundFields.
                Field f = delegate.getClass().getDeclaredField("boundFields");
                f.setAccessible(true);
                Map boundFields = (Map) f.get(delegate);

                // Then replace it with our implementation throwing exception if the value is null.
                boundFields = new LinkedHashMap(boundFields) {

                    @Override
                    public Object get(Object key) {

                        Object value = super.get(key);
                        if (value == null) {
                            throw new JsonParseException("invalid property name: " + key);
                        }
                        return value;

                    }

                };
                // Finally, push our custom map back using reflection.
                f.set(delegate, boundFields);

            } catch (Exception e) {
                // Should never happen if the implementation doesn't change.
                throw new IllegalStateException(e);
            }

        }
        return delegate;
    }

}
```

**Comment by Killdozer65** [comment]
Thanks @ikus060.  I was able to adapt your approach so I can log error messages on unrecognized properties, rather than silently ignoring them as is done by default.

**Comment by ikus060** [comment]
The solution is a bit ugly, but it work...

**Comment by hardiksoni13** [comment]
Do we have this fix as part of the GSON library now ?

**Comment by adam66** [comment]
Nice work-around but I will have to adapt it to be compatible with my IdExclusionStrategy that tells gson to ignore the id field.  Gson now throws errors wherever it sees the id in JSON. 

My intention is to ignore ids on serialization, and by design it would be compatible because the TypeAdaptor for this example is only implemented for gets / deserialization. However ExclusionStrategies are deserialization/serialization-agnostic - work on both.

**Comment by cynthux** [comment]
Any updates on this issue? It was bumped to "Critical" priority three years ago.

**Comment by JavierSegoviaCordoba** [comment]
Up

**Comment by tumani4** [comment]
Ок

**Comment by norbdev** [comment]
Up

**Comment by ataraxus** [comment]
wow, this is astounding... definitely moving away from gson. why is this basic feature not present?

**Comment by rubearen** [comment]
I'm looking for an alternative to gson, this problem should have been fixed in the last 10 years

**Comment by evanbross** [comment]
Still not fixed????
This seems to be a pattern with google tools, develop something 80% to 90% and then walk away from it :(

**Comment by gabrielcpaz** [comment]
up

**Comment by luca-colazzo** [comment]
Imagine not resolving an issue in 11 years

> 
> Original issue reported on code.google.com by `mperdik...@gmail.com` on 22 Jan 2010 at 10:13
> 

Oh right...

**Comment by luca-colazzo** [comment]
Imagine not resolving a critial-labeled issue in 11 years

> Original issue reported on code.google.com by `mperdik...@gmail.com` on 22 Jan 2010 at 10:13

> * Added labels: **Priority-Critical**

Oh right...

**Comment by evanbross** [comment]
This is why I've been moving away from google libraries. They have a solid
history of abandoning projects and ignoring issues with them.

**Comment by lilmayu** [comment]
This would be especially great if you are parsing a huge chunk of JSON and you are unsure if you have defined all fields.

**Comment by JavierPAYTEF** [comment]
I will check the adapter to see if I can make it work, really strange this has been around for so long

**Comment by eamonnmcmanus** [comment]
The `boundFields` field is now in the superclass of the class returned by `delegate.getClass()`. So the code should work with 2.10 if you change that line to
```java
        Field f = delegate.getClass().getSuperclass().getDeclaredField("boundFields");
```

We had to fix a couple of occurrences of the same problem in Google's internal codebase. I changed the code to this slightly more robust version:

```java
        Field f = findField(delegateAdapter.getClass(), "boundFields");
...
  private static Field findField(Class<?> startingClass, String fieldName)
      throws NoSuchFieldException {
    for (Class<?> c = startingClass; c != null; c = c.getSuperclass()) {
      try {
        return c.getDeclaredField(fieldName);
      } catch (NoSuchFieldException e) {
        // OK: continue with superclasses
      }
    }
    throw new NoSuchFieldException(fieldName + " starting from " + startingClass.getName());
  }
```

That should work with both pre- and post-2.10 versions.

Although Gson is in maintenance mode, this particular issue seems important enough that we should have some formal support for it instead of requiring people to use reflective hacks like this.

**Comment by marinat** [comment]
up

**Comment by mbonness** [comment]
As a workaround I am just checking if deserialized objects contain null fields in lieu of expecting a null object or an exception.

It would be nice if Google at least updated the documentation for `Gson.fromJson()` since this is clearly incorrect:

Returns:
an object of type T from the string. Returns null if json is null.
Throws:
[JsonParseException](https://www.javadoc.io/static/com.google.code.gson/gson/2.8.5/com/google/gson/JsonParseException.html) - if json is not a valid representation for an object of type typeOfT
[JsonSyntaxException](https://www.javadoc.io/static/com.google.code.gson/gson/2.8.5/com/google/gson/JsonSyntaxException.html) - if json is not a valid representation for an object of type

**Comment by Marcono1234** [comment]
@mbonness, I think the documentation is correct[^1]. The "an object of type T from the string. Returns null if json is null" refers to the value as a whole, not its fields. For example `gson.fromJson("null", MyClass.class)` will return `null`.

Or do you mean the documented exceptions for "if json is not a valid representation for ..."?

[^1]: At least for the default case. A custom adapter can also for JSON `null` return a non-`null` Java object and the other way around.
