### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AdamCalculator** [google/gson#2699]
# Gson version
2.9.1

# Java / Android version
21

# Used tools
- [ ] Gradle; version: 
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] [MultiLoaderTemplate](https://github.com/jaredlll08/MultiLoader-Template/)

   > Failed to setup Minecraft, java.lang.RuntimeException: Unexpected IllegalAccessException occurred (Gson 2.9.1). Certain ReflectionAccessFilter features require Java >= 9 to work correctly. If you are not using ReflectionAccessFilter, report this to the Gson maintainers.

**Comment by Marcono1234** [comment]
Thanks for the report! Could you please try the latest Gson version (currently 2.11.0) just to make sure this hasn't been fixed already in a newer version?

Also, if possible could you please create a minimal, reproducible example (as described [here](https://stackoverflow.com/help/minimal-reproducible-example)) for it?

**Comment by softy-oniguru** [comment]
```
[16:55:54 WARN]: [SkinsRestorer] Async task for SkinsRestorer v15.0.14 generated an exception
java.lang.RuntimeException: Unexpected IllegalAccessException occurred (Gson 2.11.0). Certain ReflectionAccessFilter features require Java >= 9 to work correctly. If you are not using ReflectionAccessFilter, report this to the Gson maintainers.
        at net.skinsrestorer.shadow.gson.internal.reflect.ReflectionHelper.createExceptionForUnexpectedIllegalAccess(ReflectionHelper.java:200) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:522) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.internal.bind.ReflectiveTypeAdapterFactory$2.readIntoField(ReflectiveTypeAdapterFactory.java:267) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:558) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:516) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1361) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1262) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1171) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1107) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.connections.http.HttpResponse.getBodyAs(HttpResponse.java:33) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.connections.MojangAPIImpl.getUUIDEclipse(MojangAPIImpl.java:119) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.connections.ServiceCheckerService.checkServices(ServiceCheckerService.java:54) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.plugin.SRPlugin.runServiceCheck(SRPlugin.java:440) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.bukkit.folia.FoliaSchedulerProvider.lambda$getCancellingTaskConsumer$0(FoliaSchedulerProvider.java:84) ~[SkinsRestorer.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:857) ~[?:?]
Caused by: java.lang.IllegalAccessException: Can not set final net.skinsrestorer.shared.connections.responses.EclipseCacheData$CacheState field net.skinsrestorer.shared.connections.responses.EclipseCacheData.state to net.skinsrestorer.shared.connections.responses.EclipseCacheData$CacheState
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79) ~[?:?]
        at java.lang.reflect.Field.set(Field.java:805) ~[?:?]
        at net.skinsrestorer.shadow.gson.internal.bind.ReflectiveTypeAdapterFactory$2.readIntoField(ReflectiveTypeAdapterFactory.java:278) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:558) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:516) ~[SkinsRestorer.jar:?]
        ... 16 more
```

**Comment by Marcono1234** [comment]
Thanks, it looks like `EclipseCacheData` for which the exception occurs might be a Record class, see [SkinsRestorer project code](https://github.com/SkinsRestorer/SkinsRestorer/blob/86e7b1fcf78cc7e07b3c477450d3a2671aa2a019/shared/src/main/java/net/skinsrestorer/shared/connections/responses/EclipseCacheData.java). Apparently Gson did not detect this and is trying to use the regular reflection adapter on it, which fails.

It looks like you (or rather the SkinsRestorer  project) is using a repackaged version of Gson. If possible could you please try with a non-repackaged version of Gson? Also, do you use any code shrinking tools, such as ProGuard or R8?

If possible, could you please try to debug your application and check why Gson's internal `ReflectionHelper.isRecord` does not recognize that `EclipseCacheData` is a Record class?

Maybe it would also be worth reporting this to the https://github.com/SkinsRestorer/SkinsRestorer maintainers (and linking to this issue here).

Also just to be sure, @AdamCalculator, is this the same exception you are seeing?

**Comment by AdamCalculator** [comment]
@Marcono1234 
I have already corrected my mistake somehow. The error occurred during the building of the gradle project, but it somehow corrected itself.

**Comment by Paddy69** [comment]
> [@Marcono1234](https://github.com/Marcono1234) I have already corrected my mistake somehow. The error occurred during the building of the gradle project, but it somehow corrected itself.

i have the same issue, and it has not solved it self

[message.txt](https://github.com/user-attachments/files/21048510/message.txt)

resolved; updated foojay to 1.0.0 in settings.gradle

**Comment by Marcono1234** [comment]
@Paddy69, it seems you are using Gson 2.9.1. If possible could you please try using the latest Gson version to be sure that this has not already been solved in a newer version.

~~The issue here might be similar, that somehow Gson is not recognizing the class as Record. Could you please either try to set a breakpoint and check why Gson's `ReflectionHelper.isRecord` is not recognizing the class as Record. Or try to get the compiled class file for `net.fabricmc.loom.configuration.providers.minecraft.VersionsManifest` and attach it here.~~

~~Maybe there is some tooling involved which somehow transforms the class, preventing it from being recognized as Record.~~

Edit: The issue for your case @Paddy69 is actually that you are using Gson 2.9.1; record support was only added in Gson 2.10 (see [release notes](https://github.com/google/gson/releases/tag/gson-parent-2.10)).
